# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class CatalogApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Enumerate valid values for entity_type, formation_state, and status
    # Public catalog of accepted enum values. No authentication required.
    # @return [ApiV1CatalogGet200Response]
    def api_v1_catalog_get()
      data, _status_code, _headers = api_v1_catalog_get_with_http_info()
      data
    end

    # Enumerate valid values for entity_type, formation_state, and status
    # Public catalog of accepted enum values. No authentication required.
    # @return [Array<(ApiV1CatalogGet200Response, Integer, Hash)>] ApiV1CatalogGet200Response data, response status code and response headers
    def api_v1_catalog_get_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: CatalogApi.api_v1_catalog_get ..."}
      end
      # resource path
      local_var_path = "/api/v1/catalog"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "ApiV1CatalogGet200Response"

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"CatalogApi.api_v1_catalog_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CatalogApi#api_v1_catalog_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return ApiV1CatalogGet200Response.from_json(data), status_code, headers
    end
  end
end
