# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class ClientsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List the organization's clients
    # @return [nil]
    def api_v1_clients_get()
      api_v1_clients_get_with_http_info()
      nil
    end

    # List the organization&#39;s clients
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_clients_get_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: ClientsApi.api_v1_clients_get ..."}
      end
      # resource path
      local_var_path = "/api/v1/clients"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"ClientsApi.api_v1_clients_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: ClientsApi#api_v1_clients_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Show a client
    # @param id [String] Client UUID or number (e.g. 4 or 0004)
    # @return [nil]
    def api_v1_clients_id_get(id : String)
      api_v1_clients_id_get_with_http_info(id)
      nil
    end

    # Show a client
    # @param id [String] Client UUID or number (e.g. 4 or 0004)
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_clients_id_get_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: ClientsApi.api_v1_clients_id_get ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling ClientsApi.api_v1_clients_id_get")
      end
      # resource path
      local_var_path = "/api/v1/clients/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"ClientsApi.api_v1_clients_id_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: ClientsApi#api_v1_clients_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
