# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class CourtCasesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List a court case's filings
    # @param court_case_id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [nil]
    def api_v1_court_cases_court_case_id_filings_get(court_case_id : String)
      api_v1_court_cases_court_case_id_filings_get_with_http_info(court_case_id)
      nil
    end

    # List a court case&#39;s filings
    # @param court_case_id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_court_cases_court_case_id_filings_get_with_http_info(court_case_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_court_cases_court_case_id_filings_get ..."}
      end
      # verify the required parameter "court_case_id" is set
      if @api_client.config.client_side_validation && court_case_id.nil?
        raise ArgumentError.new("Missing the required parameter 'court_case_id' when calling CourtCasesApi.api_v1_court_cases_court_case_id_filings_get")
      end
      # resource path
      local_var_path = "/api/v1/court_cases/{court_case_id}/filings".sub("{" + "court_case_id" + "}", URI.encode_path(court_case_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_court_cases_court_case_id_filings_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_court_cases_court_case_id_filings_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Record a court filing
    # document is the as-filed copy, already filed under the case's matter. With endorsed (the court's stamped PDF) the PDF becomes an asset of that document and its filed copy, the filing is accepted on filed_on, and case_number and filed_on are written to the court case with that document as the source. Without endorsed the filing is submitted and case_number / filed_on are refused.
    # @param court_case_id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [nil]
    def api_v1_court_cases_court_case_id_filings_post(court_case_id : String)
      api_v1_court_cases_court_case_id_filings_post_with_http_info(court_case_id)
      nil
    end

    # Record a court filing
    # document is the as-filed copy, already filed under the case&#39;s matter. With endorsed (the court&#39;s stamped PDF) the PDF becomes an asset of that document and its filed copy, the filing is accepted on filed_on, and case_number and filed_on are written to the court case with that document as the source. Without endorsed the filing is submitted and case_number / filed_on are refused.
    # @param court_case_id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_court_cases_court_case_id_filings_post_with_http_info(court_case_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_court_cases_court_case_id_filings_post ..."}
      end
      # verify the required parameter "court_case_id" is set
      if @api_client.config.client_side_validation && court_case_id.nil?
        raise ArgumentError.new("Missing the required parameter 'court_case_id' when calling CourtCasesApi.api_v1_court_cases_court_case_id_filings_post")
      end
      # resource path
      local_var_path = "/api/v1/court_cases/{court_case_id}/filings".sub("{" + "court_case_id" + "}", URI.encode_path(court_case_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["multipart/form-data"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_court_cases_court_case_id_filings_post",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_court_cases_court_case_id_filings_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Show a court case with its filings and the source of each fact
    # @param id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [nil]
    def api_v1_court_cases_id_get(id : String)
      api_v1_court_cases_id_get_with_http_info(id)
      nil
    end

    # Show a court case with its filings and the source of each fact
    # @param id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_court_cases_id_get_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_court_cases_id_get ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling CourtCasesApi.api_v1_court_cases_id_get")
      end
      # resource path
      local_var_path = "/api/v1/court_cases/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_court_cases_id_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_court_cases_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Change a court case's non-fact fields
    # Changes court_name, efsp, efsp_reference or status. case_number and filed_on are refused: record a filing with the endorsed copy instead.
    # @param id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [nil]
    def api_v1_court_cases_id_patch(id : String, api_v1_court_cases_id_patch_request : ApiV1CourtCasesIdPatchRequest?)
      api_v1_court_cases_id_patch_with_http_info(id, api_v1_court_cases_id_patch_request)
      nil
    end

    # Change a court case&#39;s non-fact fields
    # Changes court_name, efsp, efsp_reference or status. case_number and filed_on are refused: record a filing with the endorsed copy instead.
    # @param id [String] Court case UUID, its case number, or the matter number when the matter has one case
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_court_cases_id_patch_with_http_info(id : String, api_v1_court_cases_id_patch_request : ApiV1CourtCasesIdPatchRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_court_cases_id_patch ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling CourtCasesApi.api_v1_court_cases_id_patch")
      end
      # resource path
      local_var_path = "/api/v1/court_cases/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = api_v1_court_cases_id_patch_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_court_cases_id_patch",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_court_cases_id_patch\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # List a matter's court cases
    # @param matter_id [String] Matter UUID or number (e.g. 0004-001)
    # @return [nil]
    def api_v1_matters_matter_id_court_cases_get(matter_id : String)
      api_v1_matters_matter_id_court_cases_get_with_http_info(matter_id)
      nil
    end

    # List a matter&#39;s court cases
    # @param matter_id [String] Matter UUID or number (e.g. 0004-001)
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_matters_matter_id_court_cases_get_with_http_info(matter_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_matters_matter_id_court_cases_get ..."}
      end
      # verify the required parameter "matter_id" is set
      if @api_client.config.client_side_validation && matter_id.nil?
        raise ArgumentError.new("Missing the required parameter 'matter_id' when calling CourtCasesApi.api_v1_matters_matter_id_court_cases_get")
      end
      # resource path
      local_var_path = "/api/v1/matters/{matter_id}/court_cases".sub("{" + "matter_id" + "}", URI.encode_path(matter_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_matters_matter_id_court_cases_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_matters_matter_id_court_cases_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Open a court case (before filing)
    # Opens a case shell with the intended court. The case number and filed date are facts: only a filing with the endorsed copy sets them (POST /api/v1/court_cases/{id}/filings).
    # @param matter_id [String] Matter UUID or number (e.g. 0004-001)
    # @return [nil]
    def api_v1_matters_matter_id_court_cases_post(matter_id : String, api_v1_matters_matter_id_court_cases_post_request : ApiV1MattersMatterIdCourtCasesPostRequest?)
      api_v1_matters_matter_id_court_cases_post_with_http_info(matter_id, api_v1_matters_matter_id_court_cases_post_request)
      nil
    end

    # Open a court case (before filing)
    # Opens a case shell with the intended court. The case number and filed date are facts: only a filing with the endorsed copy sets them (POST /api/v1/court_cases/{id}/filings).
    # @param matter_id [String] Matter UUID or number (e.g. 0004-001)
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_matters_matter_id_court_cases_post_with_http_info(matter_id : String, api_v1_matters_matter_id_court_cases_post_request : ApiV1MattersMatterIdCourtCasesPostRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: CourtCasesApi.api_v1_matters_matter_id_court_cases_post ..."}
      end
      # verify the required parameter "matter_id" is set
      if @api_client.config.client_side_validation && matter_id.nil?
        raise ArgumentError.new("Missing the required parameter 'matter_id' when calling CourtCasesApi.api_v1_matters_matter_id_court_cases_post")
      end
      # resource path
      local_var_path = "/api/v1/matters/{matter_id}/court_cases".sub("{" + "matter_id" + "}", URI.encode_path(matter_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = api_v1_matters_matter_id_court_cases_post_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"CourtCasesApi.api_v1_matters_matter_id_court_cases_post",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CourtCasesApi#api_v1_matters_matter_id_court_cases_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
