# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class DocumentsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Delete a document
    # @param id [String] 
    # @return [nil]
    def api_v1_documents_id_delete(id : String)
      api_v1_documents_id_delete_with_http_info(id)
      nil
    end

    # Delete a document
    # @param id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_documents_id_delete_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DocumentsApi.api_v1_documents_id_delete ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling DocumentsApi.api_v1_documents_id_delete")
      end
      # resource path
      local_var_path = "/api/v1/documents/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DocumentsApi.api_v1_documents_id_delete",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DocumentsApi#api_v1_documents_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Show a document
    # @param id [String] 
    # @return [nil]
    def api_v1_documents_id_get(id : String)
      api_v1_documents_id_get_with_http_info(id)
      nil
    end

    # Show a document
    # @param id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_documents_id_get_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DocumentsApi.api_v1_documents_id_get ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling DocumentsApi.api_v1_documents_id_get")
      end
      # resource path
      local_var_path = "/api/v1/documents/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DocumentsApi.api_v1_documents_id_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DocumentsApi#api_v1_documents_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Update document metadata (tags, name)
    # @param id [String] 
    # @return [nil]
    def api_v1_documents_id_patch(id : String, api_v1_documents_id_patch_request : ApiV1DocumentsIdPatchRequest?)
      api_v1_documents_id_patch_with_http_info(id, api_v1_documents_id_patch_request)
      nil
    end

    # Update document metadata (tags, name)
    # @param id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_documents_id_patch_with_http_info(id : String, api_v1_documents_id_patch_request : ApiV1DocumentsIdPatchRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DocumentsApi.api_v1_documents_id_patch ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling DocumentsApi.api_v1_documents_id_patch")
      end
      # resource path
      local_var_path = "/api/v1/documents/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = api_v1_documents_id_patch_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"DocumentsApi.api_v1_documents_id_patch",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DocumentsApi#api_v1_documents_id_patch\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # List documents for an entity
    # @param entity_id [String] 
    # @return [nil]
    def api_v1_entities_entity_id_documents_get(entity_id : String)
      api_v1_entities_entity_id_documents_get_with_http_info(entity_id)
      nil
    end

    # List documents for an entity
    # @param entity_id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_entities_entity_id_documents_get_with_http_info(entity_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DocumentsApi.api_v1_entities_entity_id_documents_get ..."}
      end
      # verify the required parameter "entity_id" is set
      if @api_client.config.client_side_validation && entity_id.nil?
        raise ArgumentError.new("Missing the required parameter 'entity_id' when calling DocumentsApi.api_v1_entities_entity_id_documents_get")
      end
      # resource path
      local_var_path = "/api/v1/entities/{entity_id}/documents".sub("{" + "entity_id" + "}", URI.encode_path(entity_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DocumentsApi.api_v1_entities_entity_id_documents_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DocumentsApi#api_v1_entities_entity_id_documents_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Import a PDF as an executed document
    # @param entity_id [String] 
    # @return [nil]
    def api_v1_entities_entity_id_documents_import_post(entity_id : String)
      api_v1_entities_entity_id_documents_import_post_with_http_info(entity_id)
      nil
    end

    # Import a PDF as an executed document
    # @param entity_id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_entities_entity_id_documents_import_post_with_http_info(entity_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DocumentsApi.api_v1_entities_entity_id_documents_import_post ..."}
      end
      # verify the required parameter "entity_id" is set
      if @api_client.config.client_side_validation && entity_id.nil?
        raise ArgumentError.new("Missing the required parameter 'entity_id' when calling DocumentsApi.api_v1_entities_entity_id_documents_import_post")
      end
      # resource path
      local_var_path = "/api/v1/entities/{entity_id}/documents/import".sub("{" + "entity_id" + "}", URI.encode_path(entity_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["multipart/form-data"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DocumentsApi.api_v1_entities_entity_id_documents_import_post",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DocumentsApi#api_v1_entities_entity_id_documents_import_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
