# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class EntitiesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List entities in the token's organization
    # @return [ApiV1EntitiesGet200Response]
    def api_v1_entities_get()
      data, _status_code, _headers = api_v1_entities_get_with_http_info()
      data
    end

    # List entities in the token&#39;s organization
    # @return [Array<(ApiV1EntitiesGet200Response, Integer, Hash)>] ApiV1EntitiesGet200Response data, response status code and response headers
    def api_v1_entities_get_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: EntitiesApi.api_v1_entities_get ..."}
      end
      # resource path
      local_var_path = "/api/v1/entities"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "ApiV1EntitiesGet200Response"

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"EntitiesApi.api_v1_entities_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EntitiesApi#api_v1_entities_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return ApiV1EntitiesGet200Response.from_json(data), status_code, headers
    end

    # Show an entity in the token's organization
    # @param id [String] Entity UUID
    # @return [ApiV1EntitiesIdGet200Response]
    def api_v1_entities_id_get(id : String)
      data, _status_code, _headers = api_v1_entities_id_get_with_http_info(id)
      data
    end

    # Show an entity in the token&#39;s organization
    # @param id [String] Entity UUID
    # @return [Array<(ApiV1EntitiesIdGet200Response, Integer, Hash)>] ApiV1EntitiesIdGet200Response data, response status code and response headers
    def api_v1_entities_id_get_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: EntitiesApi.api_v1_entities_id_get ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling EntitiesApi.api_v1_entities_id_get")
      end
      # resource path
      local_var_path = "/api/v1/entities/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "ApiV1EntitiesIdGet200Response"

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"EntitiesApi.api_v1_entities_id_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EntitiesApi#api_v1_entities_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return ApiV1EntitiesIdGet200Response.from_json(data), status_code, headers
    end

    # Create an entity in the token's organization
    # @return [nil]
    def api_v1_entities_post(api_v1_entities_post_request : ApiV1EntitiesPostRequest?)
      api_v1_entities_post_with_http_info(api_v1_entities_post_request)
      nil
    end

    # Create an entity in the token&#39;s organization
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_entities_post_with_http_info(api_v1_entities_post_request : ApiV1EntitiesPostRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: EntitiesApi.api_v1_entities_post ..."}
      end
      # resource path
      local_var_path = "/api/v1/entities"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = api_v1_entities_post_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"EntitiesApi.api_v1_entities_post",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EntitiesApi#api_v1_entities_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
