# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "uri"

module RightDocuments
  class TemplatesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create a template in the token's organization
    # @return [nil]
    def api_v1_templates_post(api_v1_templates_post_request : ApiV1TemplatesPostRequest?)
      api_v1_templates_post_with_http_info(api_v1_templates_post_request)
      nil
    end

    # Create a template in the token&#39;s organization
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_templates_post_with_http_info(api_v1_templates_post_request : ApiV1TemplatesPostRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: TemplatesApi.api_v1_templates_post ..."}
      end
      # resource path
      local_var_path = "/api/v1/templates"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = api_v1_templates_post_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"TemplatesApi.api_v1_templates_post",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: TemplatesApi#api_v1_templates_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
