# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::CatalogApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "CatalogApi" do
  describe "test an instance of CatalogApi" do
    it "should create an instance of CatalogApi" do
      api_instance = RightDocuments::CatalogApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::CatalogApi)
    end
  end

  # unit tests for api_v1_catalog_get
  # Enumerate valid values for entity_type, formation_state, and status
  # Public catalog of accepted enum values. No authentication required.
  # @param [Hash] opts the optional parameters
  # @return [ApiV1CatalogGet200Response]
  describe "api_v1_catalog_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
