# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ClientsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ClientsApi" do
  describe "test an instance of ClientsApi" do
    it "should create an instance of ClientsApi" do
      api_instance = RightDocuments::ClientsApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::ClientsApi)
    end
  end

  # unit tests for api_v1_clients_get
  # List the organization&#39;s clients
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_clients_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_clients_id_get
  # Show a client
  # @param id Client UUID or number (e.g. 4 or 0004)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_clients_id_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
