# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::CourtCasesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "CourtCasesApi" do
  describe "test an instance of CourtCasesApi" do
    it "should create an instance of CourtCasesApi" do
      api_instance = RightDocuments::CourtCasesApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::CourtCasesApi)
    end
  end

  # unit tests for api_v1_court_cases_court_case_id_filings_get
  # List a court case&#39;s filings
  # @param court_case_id Court case UUID, its case number, or the matter number when the matter has one case
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_court_cases_court_case_id_filings_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_court_cases_court_case_id_filings_post
  # Record a court filing
  # document is the as-filed copy, already filed under the case&#39;s matter. With endorsed (the court&#39;s stamped PDF) the PDF becomes an asset of that document and its filed copy, the filing is accepted on filed_on, and case_number and filed_on are written to the court case with that document as the source. Without endorsed the filing is submitted and case_number / filed_on are refused.
  # @param court_case_id Court case UUID, its case number, or the matter number when the matter has one case
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_court_cases_court_case_id_filings_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_court_cases_id_get
  # Show a court case with its filings and the source of each fact
  # @param id Court case UUID, its case number, or the matter number when the matter has one case
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_court_cases_id_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_court_cases_id_patch
  # Change a court case&#39;s non-fact fields
  # Changes court_name, efsp, efsp_reference or status. case_number and filed_on are refused: record a filing with the endorsed copy instead.
  # @param id Court case UUID, its case number, or the matter number when the matter has one case
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1CourtCasesIdPatchRequest] :api_v1_court_cases_id_patch_request 
  # @return [nil]
  describe "api_v1_court_cases_id_patch test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_court_cases_get
  # List a matter&#39;s court cases
  # @param matter_id Matter UUID or number (e.g. 0004-001)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_matter_id_court_cases_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_court_cases_post
  # Open a court case (before filing)
  # Opens a case shell with the intended court. The case number and filed date are facts: only a filing with the endorsed copy sets them (POST /api/v1/court_cases/{id}/filings).
  # @param matter_id Matter UUID or number (e.g. 0004-001)
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1MattersMatterIdCourtCasesPostRequest] :api_v1_matters_matter_id_court_cases_post_request 
  # @return [nil]
  describe "api_v1_matters_matter_id_court_cases_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
