# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::DocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "DocumentsApi" do
  describe "test an instance of DocumentsApi" do
    it "should create an instance of DocumentsApi" do
      api_instance = RightDocuments::DocumentsApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::DocumentsApi)
    end
  end

  # unit tests for api_v1_documents_id_get
  # Show a document
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_documents_id_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_entities_entity_id_documents_get
  # List documents for an entity
  # @param entity_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_entities_entity_id_documents_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_entities_entity_id_documents_import_post
  # Import a PDF as an executed document
  # @param entity_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_entities_entity_id_documents_import_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
