# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::EntitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "EntitiesApi" do
  describe "test an instance of EntitiesApi" do
    it "should create an instance of EntitiesApi" do
      api_instance = RightDocuments::EntitiesApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::EntitiesApi)
    end
  end

  # unit tests for api_v1_entities_get
  # List entities in the token&#39;s organization
  # @param [Hash] opts the optional parameters
  # @return [ApiV1EntitiesGet200Response]
  describe "api_v1_entities_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_entities_post
  # Create an entity in the token&#39;s organization
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1EntitiesPostRequest] :api_v1_entities_post_request 
  # @return [nil]
  describe "api_v1_entities_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
