# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::MattersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "MattersApi" do
  describe "test an instance of MattersApi" do
    it "should create an instance of MattersApi" do
      api_instance = RightDocuments::MattersApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::MattersApi)
    end
  end

  # unit tests for api_v1_matters_get
  # List matters
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status open or closed
  # @option opts [String] :client Client UUID or number
  # @return [nil]
  describe "api_v1_matters_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_id_get
  # Show a matter with its parties
  # @param id Matter UUID or number (e.g. 0004-001 or 4-1)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_id_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_id_patch
  # Update a matter&#39;s settings
  # @param id Matter UUID or number (e.g. 0004-001 or 4-1)
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1MattersIdPatchRequest] :api_v1_matters_id_patch_request 
  # @return [nil]
  describe "api_v1_matters_id_patch test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_documents_get
  # List a matter&#39;s documents
  # @param matter_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_matter_id_documents_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_documents_import_post
  # Import a signed PDF under a matter
  # @param matter_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_matter_id_documents_import_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_parties_get
  # List a matter&#39;s parties
  # @param matter_id Matter UUID or number
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_matter_id_parties_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_parties_id_delete
  # Remove a party
  # @param matter_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_matters_matter_id_parties_id_delete test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_matter_id_parties_post
  # Add a party to a matter
  # @param matter_id Matter UUID or number
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1MattersMatterIdPartiesPostRequest] :api_v1_matters_matter_id_parties_post_request 
  # @return [nil]
  describe "api_v1_matters_matter_id_parties_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_matters_post
  # Open a matter for a client
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1MattersPostRequest] :api_v1_matters_post_request 
  # @return [nil]
  describe "api_v1_matters_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
