# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::MeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "MeApi" do
  describe "test an instance of MeApi" do
    it "should create an instance of MeApi" do
      api_instance = RightDocuments::MeApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::MeApi)
    end
  end

  # unit tests for api_v1_me_get
  # Returns the user and the token-bound organization
  # @param [Hash] opts the optional parameters
  # @return [ApiV1MeGet200Response]
  describe "api_v1_me_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
