# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "TemplatesApi" do
  describe "test an instance of TemplatesApi" do
    it "should create an instance of TemplatesApi" do
      api_instance = RightDocuments::TemplatesApi.new
      # TODO expect(api_instance).to be_instance_of(RightDocuments::TemplatesApi)
    end
  end

  # unit tests for api_v1_templates_post
  # Create a template in the token&#39;s organization
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1TemplatesPostRequest] :api_v1_templates_post_request 
  # @return [nil]
  describe "api_v1_templates_post test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
