# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1EntitiesGet200ResponseEntitiesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1EntitiesGet200ResponseEntitiesInner do

  describe "test an instance of ApiV1EntitiesGet200ResponseEntitiesInner" do
    it "should create an instance of ApiV1EntitiesGet200ResponseEntitiesInner" do
      #instance = RightDocuments::ApiV1EntitiesGet200ResponseEntitiesInner.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1EntitiesGet200ResponseEntitiesInner)
    end
  end
  describe "test attribute 'id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'entity_type'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'state'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'formation_date'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
