# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1MattersIdPatchRequestMatter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1MattersIdPatchRequestMatter do

  describe "test an instance of ApiV1MattersIdPatchRequestMatter" do
    it "should create an instance of ApiV1MattersIdPatchRequestMatter" do
      #instance = RightDocuments::ApiV1MattersIdPatchRequestMatter.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1MattersIdPatchRequestMatter)
    end
  end
  describe "test attribute 'name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'matter_type'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["advisory", "pre_litigation", "litigation"])
      # validator.allowable_values.each do |value|
      #   expect { instance.matter_type = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'our_role'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["plaintiff", "defendant", "claimant", "respondent", "advisor"])
      # validator.allowable_values.each do |value|
      #   expect { instance.our_role = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["open", "closed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.status = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'opened_on'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'closed_on'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'outcome'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
