# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1DocumentsDocumentIdDeliveriesMailPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1DocumentsDocumentIdDeliveriesMailPostRequest do

  describe "test an instance of ApiV1DocumentsDocumentIdDeliveriesMailPostRequest" do
    it "should create an instance of ApiV1DocumentsDocumentIdDeliveriesMailPostRequest" do
      #instance = RightDocuments::ApiV1DocumentsDocumentIdDeliveriesMailPostRequest.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1DocumentsDocumentIdDeliveriesMailPostRequest)
    end
  end
  describe "test attribute 'party_id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'extra_service'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["certified", "certified_return_receipt"])
      # validator.allowable_values.each do |value|
      #   expect { instance.extra_service = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'confirm'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
