# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1MattersMatterIdCourtCasesPostRequestCourtCase
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1MattersMatterIdCourtCasesPostRequestCourtCase do

  describe "test an instance of ApiV1MattersMatterIdCourtCasesPostRequestCourtCase" do
    it "should create an instance of ApiV1MattersMatterIdCourtCasesPostRequestCourtCase" do
      #instance = RightDocuments::ApiV1MattersMatterIdCourtCasesPostRequestCourtCase.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1MattersMatterIdCourtCasesPostRequestCourtCase)
    end
  end
  describe "test attribute 'court_name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'court_code'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'case_type'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["limited", "unlimited", "other"])
      # validator.allowable_values.each do |value|
      #   expect { instance.case_type = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'jury_demanded'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'efsp'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
