# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1MeGet200ResponseUser
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1MeGet200ResponseUser do

  describe "test an instance of ApiV1MeGet200ResponseUser" do
    it "should create an instance of ApiV1MeGet200ResponseUser" do
      #instance = RightDocuments::ApiV1MeGet200ResponseUser.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1MeGet200ResponseUser)
    end
  end
  describe "test attribute 'id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'email'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
