# #RightDocuments API
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.10.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for RightDocuments::ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RightDocuments::ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery do

  describe "test an instance of ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery" do
    it "should create an instance of ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery" do
      #instance = RightDocuments::ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery.new
      #expect(instance).to be_instance_of(RightDocuments::ApiV1DocumentsDocumentIdDeliveriesIdPatchRequestDelivery)
    end
  end
  describe "test attribute 'status'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["queued", "sent", "delivered", "failed", "unknown"])
      # validator.allowable_values.each do |value|
      #   expect { instance.status = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'delivered_at'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tracking_url'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'provider_id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'notes'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
